package rules

const (
	NodeCall             = "call"
	NodeCallExpression   = "call_expression"
	NodeMacroInvocation  = "macro_invocation"
	NodeBlock            = "block"
	NodeIdentifier       = "identifier"
	NodeDecorator        = "decorator"
	NodeDecoratedDef     = "decorated_definition"
	NodeClassDef         = "class_definition"
	NodeFunctionDef      = "function_definition"
	NodeFunctionItem     = "function_item"
	NodeMethodDecl       = "method_declaration"
	NodeMethodInvocation = "method_invocation"
	NodeObjectCreation   = "object_creation_expression"
	NodeWhileStatement   = "while_statement"
	NodeWhileExpression  = "while_expression"
	NodeLoopExpression   = "loop_expression"
	NodeAttributeItem    = "attribute_item"
	NodeLineComment      = "line_comment"
	NodeBlockComment     = "block_comment"
	NodeParameters       = "parameters"
	NodeParameter        = "parameter"
	NodeFormalParameters = "formal_parameters"
	NodeFormalParameter  = "formal_parameter"
	NodeSpreadParameter  = "spread_parameter"
	NodeModifiers        = "modifiers"
	NodeMarkerAnnotation = "marker_annotation"
	NodeAnnotation       = "annotation"
	NodeTypeIdentifier   = "type_identifier"
	NodeIntegralType     = "integral_type"
	NodeFloatingPoint    = "floating_point_type"
	NodeBooleanType      = "boolean_type"
	NodePrimitiveType    = "primitive_type"
	NodeReferenceType    = "reference_type"
	NodeBooleanLiteral   = "boolean_literal"
	NodeParenthesized    = "parenthesized_expression"
	NodeClassBody        = "class_body"
)
