package rules

const (
	NodeCall             = "call"
	NodeCallExpression   = "call_expression"
	NodeMacroInvocation  = "macro_invocation"
	NodeBlock            = "block"
	NodeIdentifier       = "identifier"
	NodeDecorator        = "decorator"
	NodeDecoratedDef     = "decorated_definition"
	NodeClassDef         = "class_definition"
	NodeFunctionDef      = "function_definition"
	NodeFunctionItem     = "function_item"
	NodeMethodDecl       = "method_declaration"
	NodeMethodInvocation = "method_invocation"
	NodeObjectCreation   = "object_creation_expression"
	NodeWhileStatement   = "while_statement"
	NodeWhileExpression  = "while_expression"
	NodeLoopExpression   = "loop_expression"
	NodeAttributeItem    = "attribute_item"
	NodeLineComment      = "line_comment"
	NodeBlockComment     = "block_comment"
	NodeParameters       = "parameters"
	NodeParameter        = "parameter"
	NodeFormalParameters = "formal_parameters"
	NodeFormalParameter  = "formal_parameter"
	NodeSpreadParameter  = "spread_parameter"
	NodeModifiers        = "modifiers"
	NodeMarkerAnnotation = "marker_annotation"
	NodeAnnotation       = "annotation"
	NodeTypeIdentifier   = "type_identifier"
	NodeIntegralType     = "integral_type"
	NodeFloatingPoint    = "floating_point_type"
	NodeBooleanType      = "boolean_type"
	NodePrimitiveType    = "primitive_type"
	NodeReferenceType    = "reference_type"
	NodeBooleanLiteral   = "boolean_literal"
	NodeTrue             = "true"
	NodePythonTrue       = "True"
	NodeParenthesized    = "parenthesized_expression"
	NodeClassBody        = "class_body"

	// C# (.NET) specific nodes
	NodeClassDecl              = "class_declaration"
	NodeMethodDeclaration      = "method_declaration"
	NodeAttributeList          = "attribute_list"
	NodeAttribute              = "attribute"
	NodeParameterList          = "parameter_list"
	NodeParameterDecl          = "parameter"
	NodePredefinedType         = "predefined_type"
	NodeNullableType           = "nullable_type"
	NodeGenericName            = "generic_name"
	NodeUsingDirective         = "using_directive"
	NodeInvocationExpression   = "invocation_expression"
	NodeObjectCreationExpr     = "object_creation_expression"
	NodeWhileStatementCS       = "while_statement"
	NodeForStatementCS         = "for_statement"
	NodeDeclarationBody        = "declaration_list"
	NodeMemberAccessExpression = "member_access_expression"

	// TypeScript specific nodes
	NodeExportStatement    = "export_statement"
	NodeFunctionDecl       = "function_declaration"
	NodeArrowFunction      = "arrow_function"
	NodeVariableDecl       = "variable_declarator"
	NodeImportStatement    = "import_statement"
	NodeCallExpressionTS   = "call_expression"
	NodeMemberExpression   = "member_expression"
	NodePropertyIdentifier = "property_identifier"
	NodeWhileStatementTS   = "while_statement"
	NodeForStatement       = "for_statement"
	NodeStringContent      = "string_fragment"
	NodeNewExpression      = "new_expression"
	NodeStatementBlock     = "statement_block"
	NodeLexicalDeclaration = "lexical_declaration"
	NodeRequiredParameter  = "required_parameter"
	NodeOptionalParameter  = "optional_parameter"
	NodeTypeAnnotation     = "type_annotation"
	NodeFormalParametersTS = "formal_parameters"
)
